repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.95.6
    hooks:
      - id: trufflehog
  - repo: local
    hooks:
      - id: semgrep-docker
        name: Semgrep
        language: docker_image
        entry: semgrep/semgrep:1.99.0 semgrep
        pass_filenames: false
        args: ["--config", "p/ci", "--error"]
