repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        language: system
        entry: trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail --trust-local-git-config
        pass_filenames: false
      - id: semgrep
        name: Semgrep
        language: system
        entry: semgrep
        pass_filenames: false
        args: ["--config", "p/ci", "--error"]
