repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        language: system
        entry: trufflehog filesystem . --exclude-paths .trufflehog-exclude --fail --fail-on-scan-errors --no-update --results=verified,unknown
        pass_filenames: false
      - id: semgrep
        name: Semgrep
        language: system
        entry: semgrep
        pass_filenames: false
        args: ["--config", "p/ci", "--error"]
